'use strict';
const {docs,sites,stages,A,P,T,N}=window.ARG;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[\s\-‐‑–—ー:：/年月日・　]/g,'');
const KEY='nagihara-arg-v1';
const emptyState=(resetAt=0)=>({done:[false,false,false,false,false,false],seen:[],notes:'',started:Date.now(),hints:[],resetAt,notesUpdatedAt:0});
let state=emptyState(),storageOK=true;
function readProgress(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&Array.isArray(s.done)&&s.done.length===6&&Array.isArray(s.seen)){const clean=emptyState();for(const field of Object.keys(clean))if(Object.prototype.hasOwnProperty.call(s,field))clean[field]=s[field];clean.seen=clean.seen.filter(id=>docs.some(d=>d.id===id));return clean;}}catch{storageOK=false;}return null;}
function mergeProgress(a,b){
 if(a.resetAt!==b.resetAt)return a.resetAt>b.resetAt?a:b;
 const latestNotes=a.notesUpdatedAt===b.notesUpdatedAt?(a.notes>=b.notes?a:b):(a.notesUpdatedAt>b.notesUpdatedAt?a:b);
 return {...a,done:a.done.map((done,i)=>done||b.done[i]),
  seen:[...new Set([...a.seen,...b.seen])],hints:[...new Set([...a.hints,...b.hints])],
  notes:latestNotes.notes,notesUpdatedAt:latestNotes.notesUpdatedAt,started:Math.min(a.started,b.started)};
}
function syncProgress(){const saved=readProgress();if(saved)state=mergeProgress(state,saved);return saved;}
const save=(notesChanged=false)=>{if(notesChanged)state.notesUpdatedAt=Math.max(Date.now(),state.notesUpdatedAt+1);syncProgress();try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;}};
function progressSignature(s){return JSON.stringify({...s,seen:[...s.seen].sort(),hints:[...s.hints].sort()});}
function refreshProgress(){
 const saved=syncProgress();
 // Merge before writing, including when another tab saved concurrently.
 if(saved&&progressSignature(saved)!==progressSignature(state))save();
 // Only replace a locked page; keep answers and notes being typed in other tabs.
 if(document.querySelector('[data-progress-gate]'))render();
}
syncProgress();
const count=()=>state.done.filter(Boolean).length;
const current=()=>Math.min(state.done.findIndex(v=>!v)===-1?6:state.done.findIndex(v=>!v),5);
const markSeen=id=>{if(!state.seen.includes(id)){state.seen.push(id);save();}};
const url=(site,part='')=>`#/${site}${part?'/'+part:''}`;
function go(site,part=''){location.hash=url(site,part);}
function route(){let h=location.hash.replace(/^#\/?/,'');if(!h)return {site:'kanri',kind:'home',value:''};const [site,kind,...rest]=h.split('/');let value;try{value=decodeURIComponent(rest.join('/'));}catch{value='';}return {site,kind:kind||'home',value};}
function accessible(d){return !d.after||state.done[d.after-1];}
function searchDocs(site,query){const parts=query.normalize('NFKC').trim().split(/\s+/).map(norm).filter(Boolean);return parts.length?docs.filter(d=>d.site===site&&accessible(d)&&parts.every(p=>norm(d.title+' '+d.keys).includes(p))):[];}
function search(site,query){const q=String(query).trim();if(!q)return;go(site,'search/'+encodeURIComponent(q));}
function itemList(items){return `<ul class="news">${[...items].sort((a,b)=>b.date.localeCompare(a.date)).map(d=>`<li><time>${esc(d.date)}</time>${A(d.site,d.id,esc(d.title))}</li>`).join('')}</ul>`;}
function formField(id,label,name,placeholder=''){return `<label for="${id}">${label}</label><input id="${id}" name="${name}" autocomplete="off" required placeholder="${placeholder}">`;}
function formEnd(text){return `<button class="button">${text}</button><p class="feedback" aria-live="polite"></p></form>`;}
function home(site){
if(site==='kanri')return `<p class="section-label">PROPERTY RECORDS / 2026.09.12</p><h1>旧施設の保全記録照会</h1><p class="intro">解体済み施設の修繕依頼が、旧管理端末から再送されています。該当施設の特定にご協力ください。</p><section class="case"><div class="case-head"><span>修繕受付票 R-260912-27</span><span class="status ${state.done[5]?'complete':''}">${state.done[5]?'訂正受領・再送停止':'照合未完了'}</span></div><div class="case-body"><blockquote>外周門の内側の取手が戻りません。<br>迎え待ち1件。</blockquote><dl class="meta-grid"><dt>受信日</dt><dd>2026年9月12日 08:40</dd><dt>対象施設</dt><dd>施設番号 04 ／ 東棟</dd><dt>参照台帳</dt><dd>2019年10月版</dd><dt>発信元</dt><dd>旧・凪原団地 管理端末</dd></dl></div></section><p>凪原団地の解体完了日は、2025年8月31日です。<br>その場所には、もう門も建物も残っていません。</p>${N('公開資料から、この記録が指す施設を特定してください。調べ方は「施設番号による照会について」を参照できます。')}<section class="lookup-box"><h2>旧施設の照会</h2><form data-stage="1">${formField('facility-id','恒久施設ID','facility','例：L000')}${formEnd('施設を照会する')}</section><h2>公開資料・お知らせ</h2>${itemList(docs.filter(d=>d.site===site&&d.listed&&accessible(d)))}`;
if(site==='city')return `<p class="section-label">PUBLIC ARCHIVE / INDEX</p><h1>廃止施設・移管資料の目録</h1><p class="intro">建物がなくなっても、そこにあった出来事の記録は保存されます。</p><div class="archive-banner"><strong>施設ID・旧地番・原簿番号で照会できます。</strong><p>公開用写しの名称が読めない場合は、対応表や別紙を参照してください。</p></div><h2>利用案内・公開規程</h2>${itemList(docs.filter(d=>d.site===site&&d.listed&&accessible(d)))}`;
if(site==='nursery')return `<p class="section-label">2025.03.31 閉園 / 保存公開版</p><h1>いつものお迎えが、<br>終わったあとに。</h1><p class="intro">しおなぎ保育園は閉園しました。<br>このサイトは、園だよりと運営資料を保存しています。</p><section class="waiting-record"><span class="small">旧端末の原簿状態</span><p class="waiting-count">お迎え待ち <strong>${state.done[5]?'0':'1'}</strong> 件</p><dl class="meta-grid"><dt>原記録日</dt><dd>2025年3月31日</dd><dt>便</dt><dd>第三便</dd><dt>原簿番号</dt><dd>H-0317</dd><dt>現在の状態</dt><dd>${state.done[5]?'引継ぎ完了／訂正受領':'未受領・保存通知継続'}</dd></dl>${state.done[5]?`<p>${A('city','restored','訂正された記録を読む')}</p>`:''}</section><p>当日の人数確認は${A('nursery','day-log','最終開園日誌')}をご覧ください。<br>原簿区分は、旧送迎・引継ぎ簿の取扱規程で照会できます。</p><h2>お知らせ・園だより</h2>${itemList(docs.filter(d=>d.site===site&&d.listed&&accessible(d)))}<p class="small">保存協力：${A('blog','about','余白ログ')}</p>`;
return `<p class="section-label">NOTES LEFT BEHIND</p><h1>引っ越しの箱に、<br>入らなかったもの。</h1><p class="intro">凪原で暮らしていた人の、古い紙と記憶。</p>${itemList(docs.filter(d=>d.site===site&&d.listed&&accessible(d)))}<p class="small">記事の言葉で検索すると、古い保存記事も見つかります。</p>`;
}
function correctionForm(){if(!state.done[4])return N('訂正には、関係する出来事の照合が必要です。'+(state.done[3]?'<a href="#/case/facts">閉園日の事実を照合する</a>':'調査を進め、対象原簿と受領の根拠を確認してください。'));return `<section class="lookup-box"><h2>原記録の訂正申請</h2><form data-stage="6">${formField('fix-facility','対象施設の恒久ID','facility','F000')}${formField('fix-register','対象原簿','register','H-0000')}<label for="fix-action">処理方法</label><select id="fix-action" name="action" required><option value="">処理を選択</option><option value="new">新しい引継ぎを一件追加</option><option value="restore">除外取消と既存行への追記</option><option value="resend">最新の再送票のみを完了</option><option value="delete">解体済み施設の記録を削除</option></select>${formField('fix-person','原記録の担当者','person','氏名')}<label for="fix-status">復元する状態</label><select id="fix-status" name="status" required><option value="">状態を選択</option><option value="handover">引継ぎ完了</option><option value="left">施設から退出</option><option value="fixed">門の修理完了</option></select><div class="form-two"><div><label for="fix-date">完了日</label><input id="fix-date" type="date" name="date" required></div><div><label for="fix-time">完了時刻</label><input id="fix-time" type="time" name="time" required></div></div>${formField('fix-proof','根拠資料の受領番号','proof','受領控えに記載された番号')}${formEnd('訂正と追記を申請する')}</section>`;}
function facts(){if(!state.done[3])return '<h1>閉園日の事実照合</h1>'+N('先にH-0317の担当者を照合してください。');return `<p class="section-label">CROSS-REFERENCE / H-0317</p><h1>閉園日の事実を照合する</h1><p>原記録と公開版の不一致について、照会を受け付けています。</p><p>人物の出入、設備申告、引継物の受領、公開版の差替えについて、保存資料との対応を確認します。</p><section class="lookup-box"><form data-stage="5"><label for="wrong-edition">事実と食い違う完了票の版</label><select id="wrong-edition" name="edition" required><option value="">版を選択</option><option value="march27">2025年3月27日 割当表</option><option value="march30">2025年3月30日 追加通知</option><option value="april03">2025年4月3日 公開版</option></select>${formField('facts-register','集計から除外された原簿','register','H-0000')}<label for="facts-gate-time">第三者が門を開けて退出を補助した時刻</label><input id="facts-gate-time" type="time" name="gateTime" required><p class="small">旧保護者が当日の私的記録に残した、門を開けた時刻を照合します。</p><div class="form-two"><div><label for="facts-date">実際の引継箱受領日</label><input id="facts-date" type="date" name="date" required></div><div><label for="facts-time">実際の受領時刻</label><input id="facts-time" type="time" name="time" required></div></div>${formField('facts-proof','受領を裏付ける控えの番号','proof','受領番号')}${formEnd('関係資料を照合する')}</section>`;}
function ending(){if(!state.done[5])return N('この記録は、訂正手続きの完了後に公開されます。');return `<article class="ending"><p class="section-label">CORRECTION ACCEPTED / H-0317</p><h1>最後に出る人のために。</h1><p class="ending-lead">修繕票の備考欄に、<br>消されていた一件が戻った。</p>${T(['2025年3月31日','復元された記録'],[['17:40','三枝千尋、閉園引継ぎの準備を開始。'],['17:50','管理側の立会便が取り消された。園への連絡記録なし。'],['17:55','受領者の所在を確認するため、一時外出。'],['18:07','引継箱を取りに帰園。'],['18:12','門の内側取手の不具合を申告。'],['18:19','旧保護者の介助で退出。'],['18:32','市当直窓口でH-0317の引継箱を受領。']])}<p>建物は、昨年取り壊されている。<br>あの門の内側で、今も待っている人はいなかった。</p><p>それでも、そこに人がいたことを消していい理由にはならなかった。</p><p>来なかったのは、約束されていた管理側の受領者だった。<br>三枝千尋は、その仕事を途中で投げ出していない。戻り、助けを借り、預かった箱を渡した。</p><p>そのあとの完了票は、一度の外出を最後の退出へと書き換え、18時以降の記録を集計から外していた。公開用の除外指示は原簿にも適用され、市に残る受領控えとのつながりが切れた。</p><p>今日の通知は、壊れた門の向こうから来たものではない。移管された保存記録の中で、受領されないままだった異議が、もう一度送られてきたのだ。</p><section class="clipping"><p class="small">原票に残された申告者の追記別紙</p><blockquote>最後に残ったことを、なかったことにしないでください。<br>誰かが、外から開けてくれました。<br>それから私は、ちゃんと帰りました。</blockquote></section><p>原簿H-0317の除外が取り消され、同じ行に受領の事実が追記された。管理側の立会未実施と、門の不具合の申告も、訂正履歴に残った。</p><div class="closure-state"><span>しおなぎ保育園　第三便</span><strong>お迎え待ち　0件</strong><span>申告を受領しました。<br>引継ぎは、終了しています。</span></div><p class="end-mark">訂正受領・処理完了</p><p><a class="button secondary" href="#/kanri">訂正後の記録を見返す</a> <a class="button secondary" href="#/case/notebook">照会控えを見る</a></p></article>`;}
const inquiryNames=['恒久施設ID照会','施設保存先照会','原簿区分照会','担当職員照会','関係記録照合','原簿訂正申請'];
const inquiryRoutes=['#/kanri','#/city/doc/welfare2018','#/nursery/doc/register-rule','#/nursery/doc/duty-lookup','#/case/facts','#/city/doc/correction'];
function notebook(){return `<p class="section-label">REFERENCE FILE / R-260912-27</p><h1>照会控え</h1><p>この受付に関連する照会と、参照資料の控えです。</p>${T(['照会','受付状況'],inquiryNames.slice(0,current()+1).map((name,i)=>[`<a href="${inquiryRoutes[i]}">${name}</a>`,state.done[i]?'照合済み':'未照合']))}<label for="notes">備考</label><textarea id="notes" rows="7" placeholder="資料名、日付、番号など">${esc(state.notes)}</textarea><h2>参照資料</h2>${state.seen.length?itemList([...state.seen].reverse().map(id=>docs.find(d=>d.id===id)).filter(Boolean)):'<p class="small">参照済みの資料はありません。</p>'}`;}
function hints(){return `<p class="section-label">PLAYER SUPPORT / OUTSIDE THE STORY</p><h1>本編外のヘルプ・解答</h1><p>ここからは作品の外側の説明です。本編の資料ではありません。必要な項目だけ開いてください。</p><details><summary>遊び方と動作について</summary><p>複数の架空のサイトに残された資料を調べる、完結するミステリーです。登場する人物・団体・事件は架空です。実在の施設への連絡や訪問、ソース解析は必要ありません。</p><p>手掛かりは、この保存資料サイトと、作中からリンクする別URLのブログで確認できます。検索エンジンを使わなくても、記事一覧やブログ内の検索からたどれます。進行とメモは同じブラウザに保存されます。端末やブラウザを変更すると進行は引き継がれません。PDFには文字版もあります。</p></details>${stages.map((stage,i)=>`<details><summary>${i+1}．${stage.title}</summary>${stage.hints.map((h,n)=>`<details data-hint="${i}-${n}"><summary>ヒント ${n+1}</summary><p>${h}</p></details>`).join('')}<details data-hint="${i}-answer"><summary>答えと次の操作</summary><p>${stage.answer}</p></details></details>`).join('')}<details><summary>最初から遊び直す</summary><p>このブラウザの進行とメモを消去します。現在の記録を残す場合は、別のブラウザで開始してください。</p><button class="button secondary" id="reset">進行とメモを消去する</button></details><details><summary>この作品について</summary><p>オリジナル作品『まだ、お迎えが来ていない。』<br>制作協力：Codex</p></details><p><a class="button secondary" href="#/kanri">本編へ戻る</a></p>`;}
function render(){syncProgress();const r=route();const site=sites[r.site]?r.site:'kanri';const config=sites[site];document.body.dataset.site=site;let body='',title=config.name;
if(!sites[r.site]&&r.site!=='case'){body='<h1>ページが見つかりません</h1><p><a href="#/kanri">保存サイトのトップへ</a></p>';}
else if(r.site==='case'){body=r.kind==='facts'?facts():r.kind==='hints'?hints():notebook();title=r.kind==='hints'?'本編外のヘルプ・解答':'照会控え';}
else if(r.kind==='search'){const found=searchDocs(site,r.value);body=`<p class="section-label">ARCHIVE SEARCH</p><h1>資料の検索</h1><p>「${esc(r.value)}」の検索結果：${found.length}件</p>${found.length?found.map(d=>`<div class="result">${A(d.site,d.id,esc(d.title))}<p>${esc(d.date)} / ${esc(config.name)}</p></div>`).join(''):`<div class="empty"><p>一致する公開索引が見つかりませんでした。</p><p class="small">資料中の番号、固有の言葉、年月などでお試しください。サイトごとに検索対象が異なります。</p></div>`}`;}
else if(r.kind==='doc'){if(r.value==='restored'){body=ending();title='訂正記録';}else{const d=docs.find(d=>d.site===site&&d.id===r.value);if(!d)body='<h1>資料が見つかりません</h1><p>保存サイトのトップから資料を検索してください。</p>';else if(!accessible(d))body=`<section data-progress-gate><h1>${esc(d.title)}</h1>${N(d.after===6?'このお知らせは、訂正の受領後に公開されます。':'この関連記録は、原簿の担当者照合後に閲覧できます。H-0317の照合を進めてください。')}</section>`;else{markSeen(d.id);body=`<article class="doc"><p class="section-label">${esc(d.date)} / 保存資料</p><h1>${esc(d.title)}</h1>${d.body}</article>`;title=d.title;}}}
else body=home(site);
const isHelp=r.site==='case'&&r.kind==='hints';
document.title=title+'｜保存記録';
document.getElementById('app').innerHTML=isHelp?`<header class="header"><strong>『まだ、お迎えが来ていない。』作品サポート</strong></header><div class="layout single"><main id="content" tabindex="-1">${body}</main></div><footer class="footer">本編外のヘルプ・解答ページ</footer>`:`<div class="utility"><span>${config.en}</span><span>${config.tag}</span></div><header class="header"><a href="${url(site)}" class="brand"><span class="logo" aria-hidden="true">${config.mark}</span><span><span class="brand-name">${config.name}</span><small>${config.en}</small></span></a><div class="head-note">${config.desc}</div></header><div class="nav-wrap"><nav aria-label="サイト内のページ">${config.nav.map(([part,label])=>`<a href="${url(site,part)}">${label}</a>`).join('')}</nav></div><div class="layout"><main id="content" tabindex="-1"><p class="breadcrumb"><a href="${url(site)}">${config.name}</a> / ${r.kind==='home'?'保存公開':'資料閲覧'}</p>${body}</main><aside class="side"><section class="search-box"><h2>${site==='blog'?'このブログを検索':'サイト内資料検索'}</h2><form id="search"><label class="small" for="query">${config.search}</label><div class="search-row"><input id="query" name="query" type="search" placeholder="キーワード" value="${r.kind==='search'?esc(r.value):''}" required><button>検索</button></div></form><p class="small">${config.hint}</p></section><section class="tools"><p class="small">照会窓口</p><a href="#/case/notebook">照会控え <span>${state.seen.length} 資料</span></a>${state.done[3]&&!state.done[4]?'<a href="#/case/facts">閉園日の事実照合</a>':''}${state.done[4]&&!state.done[5]?A('city','correction','原記録の訂正へ'):''}${state.done[5]?A('city','restored','訂正受領記録'):''}</section></aside></div><footer class="footer"><span>${config.footer}</span></footer>${!storageOK?'<p class="storage-warning" role="status">照会控えを保存できません。画面を閉じると、この閲覧中の記録が失われます。</p>':''}`;
const cf=document.querySelector('[data-correction-form]');if(cf)cf.innerHTML=correctionForm();
const sf=document.getElementById('search');if(sf)sf.addEventListener('submit',e=>{e.preventDefault();search(site,new FormData(sf).get('query'));});
document.querySelectorAll('form[data-stage]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();submitStage(Number(f.dataset.stage),Object.fromEntries(new FormData(f)),f);}));
const notes=document.getElementById('notes');if(notes)notes.addEventListener('input',()=>{state.notes=notes.value;save(true);});
document.querySelectorAll('[data-hint]').forEach(e=>e.addEventListener('toggle',()=>{if(e.open&&!state.hints.includes(e.dataset.hint)){state.hints.push(e.dataset.hint);save();}}));
const reset=document.getElementById('reset');if(reset)reset.addEventListener('click',()=>{if(window.confirm('このブラウザの進行とメモを消去し、最初から始めますか？')){syncProgress();state=emptyState(Math.max(Date.now(),state.resetAt+1));save();go('kanri');render();}});
}
function submitStage(n,data,form){syncProgress();const out=form?.querySelector('.feedback');const say=(m,good=false)=>{if(out){out.innerHTML=m;out.classList.toggle('success',good);out.setAttribute('tabindex','-1');out.focus();}return {ok:good,message:m.replace(/<[^>]+>/g,'')};};
if(n>1&&!state.done[n-2])return say('先行する照会の受付が未完了です。<a href="#/case/notebook">照会控えを確認する</a>');
let valid=false,message='記録が一致しません。資料の版、番号、対象の欄をもう一度確認してください。';
if(n===1){valid=norm(data.facility)==='f040';message='施設を照合しました。恒久施設ID F040。<br>'+A('city','demolition-file','市の解体対象照合票を開く')+'。旧名称と保存先を確認してください。';}
if(n===2){valid=['しおなぎ保育園','汐凪保育園'].includes(norm(data.facility));message='保存先を確認しました。<br><a href="#/nursery">しおなぎ保育園の保存サイトを開く</a>。';}
if(n===3){valid=data.kind==='handover'&&norm(data.time)==='1710';message='H-0317は、職員の閉園引継ぎ記録です。園児は全員降園しています。<br>'+A('nursery','duty-lookup','担当職員を照合する');}
if(n===4){valid=norm(data.staff)==='s17'&&['三枝千尋','さえぐさちひろ'].includes(norm(data.person));message='担当者は三枝千尋（S-17）と一致しました。関連原記録の閲覧を開始できます。<br>'+A('nursery','entry-log','職員出入記録')+' ／ '+A('kanri','old-request','原修繕票')+'<br>旧保護者の証言は'+A('blog','outside-gate','余白ログ「門の外から」')+'に残されています。';}
if(n===5){valid=norm(data.gateTime)==='1819'&&data.edition==='april03'&&norm(data.register)==='h0317'&&data.date==='2025-03-31'&&norm(data.time)==='1832'&&norm(data.proof)==='市受202533108';message='公開版・原簿番号・第三者による退出補助の時刻・受領日時と控えの番号を照合しました。4月3日公開版は、18時以降のH-0317を除外しています。<br>'+A('city','correction','原記録の訂正・追記へ進む');}
if(n===6){valid=norm(data.facility)==='f040'&&norm(data.register)==='h0317'&&data.action==='restore'&&['三枝千尋','さえぐさちひろ'].includes(norm(data.person))&&data.status==='handover'&&data.date==='2025-03-31'&&norm(data.time)==='1832'&&norm(data.proof)==='市受202533108';message='訂正と受領事実の追記を受理しました。';}
if(!valid){let clue='値が記録と一致しません。版、番号、日時の根拠を確認してください。';if(n===1)clue='そのIDは、受付票の番号・表示・参照版のすべてとは一致しません。';if(n===3)clue='原簿区分または降園確認時刻が登録記録と一致しません。';if(n===4)clue='担当職員番号と氏名の組合せを原記録と照合できませんでした。';if(n===5)clue='公開版・原簿・門の退出補助時刻・受領控えのいずれかが一致しません。';if(n===6)clue='申請内容を原簿と受領資料に対応付けられませんでした。';return say(clue);}
state.done[n-1]=true;save();if(n===6){go('city','doc/restored');return {ok:true,message};}return say(message,true);
}
window.addEventListener('storage',event=>{if(event.key===KEY)refreshProgress();});
window.addEventListener('focus',refreshProgress);
window.addEventListener('pageshow',refreshProgress);
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);document.getElementById('content')?.focus({preventScroll:true});});
render();
const modelContext=document.modelContext;
if(modelContext?.registerTool){const ctl=new AbortController();try{Promise.resolve(modelContext.registerTool({name:'search_archive',title:'保存資料を検索',description:'指定した架空サイトの公開索引を検索し、画面へ結果を表示する。',inputSchema:{type:'object',properties:{site:{type:'string',enum:Object.keys(sites)},query:{type:'string',minLength:1}},required:['site','query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||!sites[input.site]||typeof input.query!=='string'||!input.query.trim())throw new Error('サイトと検索語が必要です。');search(input.site,input.query);await new Promise(resolve=>setTimeout(resolve,0));return {site:input.site,results:searchDocs(input.site,input.query).map(d=>({title:d.title,route:url(d.site,'doc/'+d.id)}))};}},{signal:ctl.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>ctl.abort(),{once:true});}

